name: crypto_info
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.4
  dio: 4.0.4
  equatable: 2.0.3
  fl_chart: 0.41.0
  flutter_bloc: 8.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.1.0
  flutter_svg: 1.0.3
  intl: 0.17.0
  json_annotation: 4.4.0
  retrofit: 3.0.1
  logger: 1.1.0
  get_it: 7.2.0
  shimmer: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 9.0.2
  build_runner: 2.1.7
  change_app_package_name: 1.0.0
  dart_code_metrics: 4.9.1
  flutter_lints: 1.0.4
  flutter_launcher_icons: 0.9.2
  mockito: 5.0.17
  json_serializable: 6.1.4
  retrofit_generator: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - res/assets/
    - res/fonts/

fonts:
  - family: 'San Francisco'
    fonts:
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 100
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 200
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 300
      - asset: res/fonts/SFUIText-Regular.ttf
        weight: 400
      - asset: res/fonts/SFUIText-Medium.ttf
        weight: 500
      - asset: res/fonts/SFUIText-Semibold.ttf
        weight: 600
      - asset: res/fonts/SFUIText-Bold.ttf
        weight: 700
      - asset: res/fonts/SFUIText-Bold.ttf
        weight: 800
      - asset: res/fonts/SFUIText-Heavy.ttf
        weight: 900

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "res/icon/icon.png"
  image_path_android: "res/icon/icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "res/icon/icon_android.png"