name: crypto_info
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.3
  dio: 4.0.0
  equatable: 2.0.3
  flutter_bloc: 7.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: 4.1.0
  retrofit: 2.0.1
  logger: 1.1.0
  get_it: 7.2.0
  shimmer: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 8.1.0
  build_runner: 2.1.2
  change_app_package_name: 1.0.0
  dart_code_metrics: 4.2.1
  flutter_lints: 1.0.4
  mockito: 5.0.15
  json_serializable: 5.0.0
  retrofit_generator: 2.0.1+1

flutter:
  uses-material-design: true
  assets:
    - res/assets/
    - res/fonts/

fonts:
  - family: 'San Francisco'
    fonts:
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 100
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 200
      - asset: res/fonts/SFUIText-Light.ttf
        weight: 300
      - asset: res/fonts/SFUIText-Regular.ttf
        weight: 400
      - asset: res/fonts/SFUIText-Medium.ttf
        weight: 500
      - asset: res/fonts/SFUIText-Semibold.ttf
        weight: 600
      - asset: res/fonts/SFUIText-Bold.ttf
        weight: 700
      - asset: res/fonts/SFUIText-Bold.ttf
        weight: 800
      - asset: res/fonts/SFUIText-Heavy.ttf
        weight: 900