name: Test

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '!main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter pub run build_runner build

      - name: Run Analyze
        run: flutter analyze

      - name: Run Test
        run: flutter test